### PR TITLE
Only lookup storage specs that we actually need

### LINKED ISSUE #20: [FlinkRunner] Ingestion job tries to connect to every store available in core
## Expected Behavior
Should only connect to the relevant stores specified in the FeatureSpec.

## Current Behavior
Will pull and attempt to connect to all the stores once the job is sent to the remote Flink cluster. If there are stores it cannot connect to, the entire job will fail.

## Steps to reproduce
- Register a storage that cannot be reached (e.g. 1.2.3.4:6379)
- Run a job (not using that store) on a remote flink cluster

## Possible Solution
Since we only pull specs at the graph building stage now, ingestion shouldn't have to retrieve and cache all available stores, only the stores it needs.

### PR DESCRIPTION
**Pull request by tims**
Fixes #20 

It does some hack with the errors store spec, which we will ultimately remove when we don't get that from core.

### CODE REVIEW

File: ingestion/src/test/java/feast/ingestion/service/CompositeSpecService.java [hunk 1]
```diff
@@ -0,0 +1,78 @@
+package feast.ingestion.service;
+
+import com.google.common.collect.Lists;
+import feast.specs.EntitySpecProto.EntitySpec;
+import feast.specs.FeatureSpecProto.FeatureSpec;
+import feast.specs.StorageSpecProto.StorageSpec;
+import java.util.HashMap;
+import java.util.Map;
+
+public class CompositeSpecService implements SpecService {
```
Comment (zhilingc) [inline ingestion/src/test/java/feast/ingestion/service/CompositeSpecService.java]: Why is the `CompositeSpecService` needed for testing? Is it not sufficient to use only `MockSpecService` or `FileSpecService`?

Comment (tims) [reply ingestion/src/test/java/feast/ingestion/service/CompositeSpecService.java]: Oh yeah. That's because I need to pass in a store spec that isn't in a file during the Redis tests.

Previously I'd inject them afterwards, but Specs it tries to load referenced storage specs (from features) on construction now and aborts if it can't.

Comment (zhilingc) [reply ingestion/src/test/java/feast/ingestion/service/CompositeSpecService.java]: Is there a reason it is not possible for that spec to be in a file? Seems a bit extra

**Comment by pradithya** [comment]
@tims any chance this PR can be close? it seems it fixes #46
