### PR TITLE
Filter out extra fields, deduplicate fields in ingestion

### LINKED ISSUE #401: Missing argument in error string in ValidateFeatureRowDoFn
Too few arguments given for this error string in `feast.ingestion.transform.fn.ValidateFeatureRowDoFn: line 66`

```
 error =
              String.format(
                  "FeatureRow contains field '%s' which do not exists in FeatureSet '%s' version '%d'. Please check the FeatureRow data.",
                  field.getName(), featureSet.getReference());
```

This results in an exception being thrown instead when an incoming feature row has an additional field:
```
java.util.MissingFormatArgumentException: Format specifier '%d'
        java.util.Formatter.format(Formatter.java:2519)
        java.util.Formatter.format(Formatter.java:2455)
        java.lang.String.format(String.java:2940)
        feast.ingestion.transform.fn.ValidateFeatureRowDoFn.processElement(ValidateFeatureRowDoFn.java:66
```

### PR DESCRIPTION
**Pull request by zhilingc**
Fixes #401, but also additionally does some preprocessing of the feature row in the ValidateFeatureRowDoFn to (1) filter out extra fields and (2) deduplicate fields

I'm still not 100% sure if we want to commit to this behaviour.

Pros:
- Convenient
- Not failing when extra columns are found makes ingestion jobs more forward-compatible
- Consistent with behaviour of popular serialization methods

Cons:
- Upstream issues will not be flagged to the user
- Order of feature fields lost

That being said deduplication is not being done by field name, but the entire field, so no information should be lost.

### CODE REVIEW

File: ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java [hunk 1]
```diff
@@ -57,15 +61,12 @@ public void processElement(ProcessContext context) {
...
     if (featureSet != null) {
-
       for (FieldProto.Field field : featureRow.getFieldsList()) {
         Field fieldSpec = featureSet.getField(field.getName());
         if (fieldSpec == null) {
-          error =
-              String.format(
-                  "FeatureRow contains field '%s' which do not exists in FeatureSet '%s' version '%d'. Please check the FeatureRow data.",
-                  field.getName(), featureSet.getReference());
+          // skip
```
Comment (woop) [inline ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java]: What if we logged statistics in terms of unnecessary fields so that it doesnt result an an actual error?

File: ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java [hunk 2]
```diff
@@ -81,6 +82,7 @@ public void processElement(ProcessContext context) {
             break;
           }
         }
+        fields.add(field);
```
Comment (woop) [inline ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java]: Will a collision be happening here? And if so, how will it be handled?

**Comment by woop** [comment]
@zhilingc It's definitely a trade-off if we want to support feature rows that dont exactly comply with the feature set that has been defined, but  Ido quite like the idea of making Feast a little bit more forward-compatible and not overly brittle.

My intuition is that this approach seems sound and that it's the lesser of two evils.

File: ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java (hunk 2 above)
Comment (woop) [reply ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java]: Would it make sense to detect collision at the name level?

Comment (zhilingc) [reply ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java]: If there is a collision the 2nd element will not be written. I'm not sure if i want to commit to detecting collision at the name level at this point because it could result in data loss (that would go uncaught by the user)

File: ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java (hunk 1 above)
Comment (zhilingc) [reply ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java]: Possible, but is it possible if i opened a separate PR for this? It would involve introducing a new TupleTag (for warnings)

Comment (woop) [reply ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java]: Can't we use our metrics client here?

Comment (zhilingc) [reply ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java]: we need to bubble the error down to the metrics writing fn

File: ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java (hunk 2 above)
Comment (woop) [reply ingestion/src/main/java/feast/ingestion/transform/fn/ValidateFeatureRowDoFn.java]: Ok, so if we have two fields with the same name, what happens to the data when it is written to the store? (in the most pathological case)
